### ISSUE TITLE
express.json([options]) documentation needs example

### ISSUE THREAD

**Issue by toymachiner62** [expressjs/expressjs.com#1011]
I was looking at the express docs again the other day and noticed express.json([options]) on this page https://expressjs.com/en/4x/api.html and I see it says that this is based on body-parser. I've used body-parser many times before, but curious if express.json() is a built in replacement for an external dependency?

In either case there is no example on how to use it. Can you please add one? Is it used the exact same way as body-parser?

**Comment by wesleytodd** [comment]
Hey @toymachiner62, it is in fact just exposing `body-parser` directly (as in `express.json = bodyParser.json` [see here](https://github.com/expressjs/express/blob/master/lib/express.js#L78)).  I think the goal is to not duplicate any documentation so that we don't have to maintain it in multiple places.  That being said, there are already a bunch of doc's there coupled to the interface of `body-parser`, so if you wanted to submit a PR with an example, I think it would be helpful to have.

**Comment by toymachiner62** [comment]
Struggling to find the file in the repo that corresponds to this page. help.

**Comment by wesleytodd** [comment]
https://github.com/expressjs/expressjs.com/blob/gh-pages/_includes/api/en/4x/express.json.md

**Comment by ryhinchey** [comment]
Closing this issue as it looks like this content has been added to the site
