### ISSUE TITLE
req.headers missing from API docs

### ISSUE THREAD

**Issue by artze** [expressjs/expressjs.com#1049]
Thought it might be useful to add `req.headers` property in the API docs. I'd be happy to do the write-up if you allow.

**Comment by dougwilson** [comment]
We don't include any of the API that comes from Node.js since those APIs will vary by the Node.js version, and not by the Express.js version (and Express.js doesn't maintain them). There is a link at the top of the Request section http://expressjs.com/en/4x/api.html#req

> The req object is an enhanced version of Node’s own request object and supports all built-in fields and methods.

And that links to https://nodejs.org/api/http.html#http_class_http_incomingmessage which documents `req.headers`
