### ISSUE TITLE
strange content in security best practices page

### ISSUE THREAD

**Issue by rsr-at-mindtwin** [expressjs/expressjs.com#1090]
1. "Using the default session cookie name can open your app to attacks" - what?
2. Using hpkp is not a best practice, it's a foot cannon

**Comment by hacksparrow** [comment]
> Using the default session cookie name can open your app to attacks

If your session cookie name is named "session" (default), it gives away two things:

1. You are likely using Express (server fingerprinted)
2. Since you love defaults, even your cookie signing keys may be one from the examples or the Keygrip default: "key1", "key2", "keyboard cat", "sha1". Since I know the keys, I can tamper your session cookie at will rendering signed cookies meaningless.

> Using hpkp is not a best practice, it's a foot cannon

It is being realized over time that HKPK was actually not such a clever idea. Explained here - https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

**Comment by rsr-at-mindtwin** [comment]
If the concern is server fingerprinting, it would be better to do the right thing by default - randomize it if not configured.

**Comment by rsr-at-mindtwin** [comment]
The HPKP thing, OTOH, should just be removed.  It's bad advice.
