### ISSUE TITLE
Update docs to accommodate for SameSite=None

### ISSUE THREAD

**Issue by jakub-g** [expressjs/expressjs.com#1093]
There's several places in docs which do not document the support for `SameSite=None` cookie modifier (it was added later than the original support)

https://github.com/expressjs/expressjs.com/blob/efe692c93fb30b8408e2a01b4aaf8d8f99c7be92/_includes/api/en/4x/res-cookie.md
https://github.com/expressjs/expressjs.com/blob/7518c7aa5e8d05461010d4362afc240b8caf5cca/_includes/api/en/5x/res-cookie.md
https://github.com/expressjs/expressjs.com/blob/a5ca5b0edf437c066f7a1dfa5dc11bc4cb9981e1/_includes/readmes/session.md
https://github.com/expressjs/expressjs.com/blob/d8a41950cbf456328460407d7cfeb567d319d467/_includes/readmes/cookie-session.md

I feel like all those places should redirect to one central place in documentation, which could be the one for the underlying lib used:

https://github.com/jshttp/cookie/blob/master/README.md#samesite

**Comment by dougwilson** [comment]
Thanks for the idea, but a couple issues:

1. The cookie-session does not use the "cookie" module
2. The files under _includes/readmes we do not change, as there is a script that just pulls from their repos; their content would need to be changed in the source repo
3. For the API docs (4x, 5x) we need to keep it here, as there is no guarantee that major of Express will use whatever the master version of the cookie module is, which is why we inline the docs.

I hope that makes sense.
