### ISSUE TITLE
Documentation of maxage should be updated: value is in seconds and not msec

### ISSUE THREAD

**Issue by shaymandel** [expressjs/expressjs.com#1143]
Hi,

The documentation of serve-static mentions that maxage is measured in milliseconds. The way browsers treat this value is as seconds. The value provided in the code goes directly to the header (not divided by 1000). 
So, the documentation should be updated.
There is no bug per se - it is working, but it creates confusion.

**Comment by dougwilson** [comment]
Hi @shaymandel the documentation is regarding the JavaScript API that is being documented, nothing to do with how the web browsers work. Time-based APIs in JavaScript are typically always in milliseconds, so that is why our API is in milliseconds and not seconds -- it created much confusion to be in seconds in the JavaScript world.
