### ISSUE TITLE
res.type(type) documentation has an deprecated mime function [ mime.lookup() ]

### ISSUE THREAD

**Issue by gomes042** [expressjs/expressjs.com#1155]
URL: https://expressjs.com/en/api.html#res.type
------------------------------------------------------

According to the express.js documentation:

> Sets the Content-Type HTTP header to the MIME type as determined by **mime.lookup()** for the specified type. If type contains the “/” character, then it sets the Content-Type to type.

Everything seems to work correctly but currently the mime module seems to work as follows now:

> mime.getType(fileURL));

### mime.lookup(fileURL) is now mime.getType(fileURL)
![Untitled](https://user-images.githubusercontent.com/28831375/82506095-471cc200-9ad5-11ea-8e5c-f6cd3424d10d.png)

**Comment by gomes042** [comment]
Just out of curiosity, I'm using it in my codes as follows: `res.contentType(mime.getType(fileURL));`

**Comment by jonchurch** [comment]
You're looking at the documentation for v2 of the mime package, express is using v1.6.0 via the [`send` package](https://github.com/pillarjs/send/blob/master/package.json#L27).

I'm actually curious why we aren't using our own package [`mime-types`](https://github.com/jshttp/mime-types) in send. @dougwilson is this something we should look into?

**Comment by jonchurch** [comment]
@3GOMESz Sharp eye, by the way!

**Comment by gomes042** [comment]
Oh yes, I had noticed that, anyway would be nice to have an update on that specific part or else as you suggested, an update or exchange of the mimes-types module.



> You're looking at the documentation for v2 of the mime package, express is using v1.6.0 via the [`send` package](https://github.com/pillarjs/send/blob/master/package.json#L27).
> 
> I'm actually curious why we aren't using our own package [`mime-types`](https://github.com/jshttp/mime-types) in send. @dougwilson is this something we should look into?

**Comment by dougwilson** [comment]
@jonchurch yes, that is planned, but it is unfortunately not a silent change since the way folks add new mime types to express manipulates a global `mime` package reference...

We can clarify the API docs around this. We should really just update the docs to either (a) better describe what it does instead of saying "it does what this other thing does" or (b) make it point to `express.serveStatic.mime.lookup` instead (and add those docs if not there) or (c) just fix the link to point to the v1 of the mime module so the link actually take you to mime.lookup docs.

Those are some options I can think of in order of my own preference. Other solutions are welcome too, though changing it to mime.getType` wouldn't really make sense, as I believe that behaves slightly differently.
