### ISSUE TITLE
Website text does not get translated into the correct languages apart from the navigation

### ISSUE THREAD

**Issue by realogandrew** [expressjs/expressjs.com#1173]
When you go to a url such as https://expressjs.com/es/api.html, only the navigation is translated into the correct language whereas the rest of the body text stays in english. This is the same result for all languages that have been added into the project.

**Comment by rodion-arr** [comment]
There are no translations for API pages. As far as I see - English available only:
https://github.com/expressjs/expressjs.com/tree/gh-pages/_includes/api

**Comment by realogandrew** [comment]
There are translations for the navigation, but the rest of the content is not translatable by google because of the way the website has been built.

**Comment by rodion-arr** [comment]
That's correct, due to parts of API page are included dynamically - default page translator can't catch that.

But anyway translation of this page can be solved by google translate plugin after content fully loaded:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/5843270/88087118-1cacbb00-cb91-11ea-8388-4b6568061339.png">

**Comment by crandmck** [comment]
Yes, this is "as designed."  All the pages _except_ the API docs were translated, which is fairly typically for professional tech translation.  When IBM was doing the translation, I asked them to make an exception, but they declined.  Professional translation is spendy, so we just took what they were willing to donate.
