### ISSUE TITLE
Incorrectly placed Logo

### ISSUE THREAD

**Issue by aliaksandrsen** [expressjs/expressjs.com#1175]
![image](https://user-images.githubusercontent.com/51503682/87242968-50257200-c43a-11ea-8569-6384e3ded4e5.png)
13 inch screen

**Comment by gireeshpunathil** [comment]
@Aliaksandrsen - which browser you are using?
/cc @jonathanong - not sure this is due to the recent changes to the view because of BLM

**Comment by Aliaksandrsen** [comment]
chrome 83.0.4103.116

**Comment by aliaksandrsen** [comment]
> @Aliaksandrsen - which browser you are using?
> /cc @jonathanong - not sure this is due to the recent changes to the view because of BLM
chrome 83.0.4103.116

**Comment by rodion-arr** [comment]
This is reproducing on Russian site version even for bigger screen sizes. Looks like it is having largest menu items from all translations and current styles do not fit for them.

The problem here that even if we will shrink it to minimum space - it will still not fit before mobile version breakpoint will fire:
<img width="996" alt="Screenshot 2020-07-18 at 00 26 31" src="https://user-images.githubusercontent.com/5843270/87831973-8a08d500-c88d-11ea-9702-6b0b4e9225de.png">

Is it OK to hide search for such situation?

**Comment by crandmck** [comment]
It looks like this is just due to the length of the menu titles in Russian.  I tried it locally by shortening some of them (since I don't speak Russian, my shortened titles might not make much sense):
![Screen Shot 2020-07-26 at 2 13 19 PM](https://user-images.githubusercontent.com/2925364/88489700-b0440a00-cf4a-11ea-9f1d-e151acf93654.png)

This is on Chrome/MacOS.  

Feel free to open a PR to fix this by replacing the menu titles in [the header file](https://github.com/expressjs/expressjs.com/blob/gh-pages/_includes/header/header-ru.html) with shorter ones:
- Начальная страница
- Начало работы
- Руководство
- Справочник по API
- Расширенные возможности
- Ресурсы
