### ISSUE TITLE
Add express-actuator to Health Checks documentation

### ISSUE THREAD

**Issue by rcruzper** [expressjs/expressjs.com#1191]
I was reading the Health Check documentation and I noticed that there is only one library which adds default endpoints for health check. If you are agree I would like to create a PR to add my library [express-actuator](https://github.com/rcruzper/express-actuator) which adds default endpoints and it allows to add custom endpoints as well.

**Comment by crandmck** [comment]
Since we already list 2 other third-party OS libraries (terminus and lightship), it seems like a reasonable suggestion, but I'd like to hear from others on the @expressjs/expressjs-com team.  

However, I do think there's a general desire reduce info not DIRECTLY about Express throughout the site (even though it may be useful and _related_), to reduce maintenance work... that's the only reservation I have.

**Comment by dougwilson** [comment]
My thoughts are the same @crandmck : the request makes sense based on the current content, but in the long term, the question for how to actually maintain these are questionable.

**Comment by rcruzper** [comment]
Hi, I have added a PR in case you think it is ok to push it to the repository.
