### ISSUE TITLE
api referece -- express.static

### ISSUE THREAD

**Issue by rosald** [expressjs/expressjs.com#1253]
in property table , it says 'NOTE: express.static always sends weak ETags.'
the truth is , express.static default sends weak ETags , and can be changed by set to false.

in dotfiles chapter , is says 'NOTE: With the default value, it will not ignore files in a directory that begins with a dot.'
the truth is , With the default value, it will ignore files in a directory that begins with a dot.

**Comment by dougwilson** [comment]
Hi @rosald thanks for the feedback.

I am going to assume you are referring to the following table: http://expressjs.com/en/4x/api.html#express.static (if not, please provide the specific table you are referring to).

For the Etag comment, the note is regarding the fact that you can change etags in Express to be strong or weak, but express.static will be weak, regardless of that setting. The note is within the express.static table about enabling/disabling them, so the note is logically about the tags (when enabled) are always weak, never strong.

For the dotfiles, the note is correct as it is. If you think otherwise, it's possible just the way you worded it here is confusion. If you can provide an app that demonstrates how you think it deviates from the note, we can take a look.
