### ISSUE TITLE
URL Not Working - Comparing JavaScript Templating Engines: Jade, Mustache, Dust and More

### ISSUE THREAD

**Issue by siddhantdixit** [expressjs/expressjs.com#1290]
https://expressjs.com/en/guide/using-template-engines.html

Comparing JavaScript Templating Engines: Jade, Mustache, Dust and More

https://github.com/expressjs/expressjs.com/blob/57d0dc447717bb5e3f24bf44dfc9c9923ac4f20f/en/guide/using-template-engines.md?plain=1#L20

**Comment by Mosaab-Emam** [comment]
@dougwilson 
@aravindvnair99

This issue should be closed.

**Comment by aravindvnair99** [comment]
Thanks @Mosaab-Emam! Closing as this issue no longer exists.

Thanks for reporting @siddhantdixit!

**Comment by SergioNR** [comment]
Hello,

This issue is still happening on https://expressjs.com/en/guide/using-template-engines.html

the available URL in the text points to:
- https://strongloop.com/strongblog/compare-javascript-templates-jade-mustache-dust/

and it should point to:

- https://medium.com/@jack.yin/comparing-javascript-templating-engines-jade-mustache-dust-and-more-6a4469ac716a


Thank you
