### ISSUE TITLE
[Suggestion] Outdated translations indicator

### ISSUE THREAD

**Issue by JoaoP-Vieira** [expressjs/expressjs.com#1321]
It's important to maintain a good and updated translation of documentation. But how can people know what is updated and what is not in the translation of their language? I think it's a good idea to show this to people, because this can motivate people to update the translation and contribute for them.

A message saying: _"This document may be outdated from the English documentation. For the latest, see the English publication."_ can demotivate people to read the doc in their languages.

Instead, we can put a indication of what is really outdated.

See an example:
![Screenshot_20220203_190036](https://user-images.githubusercontent.com/71784907/152436338-187ae802-d405-4b10-ab19-dbfd84f61b2d.png)

The outdated translation is marked in red, and in the top of the page has a message saying: _"Outdated translations is marked in red"_

**Comment by dougwilson** [comment]
Thanks, I don't see anything wrong with that. If someone wants to put that together and also update it as the English part changes, we'd be happy to acccept. Unfortunately we don't have our translation service any longer, so we need volunteers to do this, which is why the generic banner was put up (since most folks contributing only speak English).

**Comment by bjohansebas** [comment]
We are going to automate the translations, so this won't be necessary.
