### ISSUE TITLE
Broken link / domain squatter link on homepage

### ISSUE THREAD

**Issue by bnoordhuis** [expressjs/expressjs.com#1496]
In the footer it says:

> Documentation translations provided by [StrongLoop/IBM](http://strongloop.com/)

Where strongloop.com redirects to `https://www.kyndryl.com/us/en` - a very generic and bland business landing page. Maybe it's an IBM thing but it's definitely not a StrongLoop thing (I'm a co-founder.)

Going by the whois records, I don't think it's an IBM thing either. I suggest either removing the link or making it point to ibm.com.

**Comment by crandmck** [comment]
Hi Ben, long time no see!  

Kyndryl is a spin-off from IBM: https://en.wikipedia.org/wiki/Kyndryl but you're right it has nothing to do with Express or Strongloop.  I don't know why strongloop.com redirects there (I haven't been at IBM for many years), but likely due to some blanket policy applied to defunct domains that IBM owns

We should just remove the link from the footer IMO (leaving just the text "IBM/Strongloop").  Alternatively, we could replace the link with https://github.com/strongloop.  Either way would be OK IMO.

We would welcome a PR if you are willing.  If not, maybe someone else can pick it up, or if I can find a moment I'll do it myself (just doing this in my spare time, call me crazy).

**Comment by bnoordhuis** [comment]
Hi Rand, long time no see indeed :-)

Opened a PR: #1497
