### ISSUE TITLE
Add GH action to update middleware READMEs

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1505]
Docs for the middleware modules linked from https://expressjs.com/en/resources/middleware.html are sourced from 
the README files in the corresponding repos and are copied to `_includes/readmes` using [get-readmes.sh](https://github.com/expressjs/expressjs.com/blob/gh-pages/get-readmes.sh). So, e.g., https://expressjs.com/en/resources/middleware/body-parser.html comes from https://github.com/expressjs/body-parser/blob/master/README.md.

Similar to #1504 this issue is a task to add a GH action to perform this task.  However, since it should run whenever any of the middleware READMEs are updated, it might require an action be added to each of those repos so that it would get triggered when that occurs....unless there's a way to detect a change to a particular file in another repo and perform an action when that happens. Since I am not an expert on GH actions, I will defer to someone who is.

Also some community docs from the expressjs/express repo are similarly reproduced on the website in [Resources > Contributing to Express](https://expressjs.com/en/resources/contributing.html), cf. https://github.com/expressjs/expressjs.com/pull/1507 and it would be great to automate that, too.

**Comment by chrisdel101** [comment]
I have no experience with this kind of thing but I am available to give this one a shot. Unless it requires admin GH permissions?

**Comment by crandmck** [comment]
Awesome!

Re admin rights, I'm not sure tbh.  Maybe @jonchurch knows.

**Comment by bjohansebas** [comment]
#1559

**Comment by bjohansebas** [comment]
@crandmck [The workflow](https://github.com/expressjs/expressjs.com/actions/runs/10555964181) could not be executed because the event `peter-evans/create-pull-request@v5` is not allowed in the repository. If allowed, we could verify if the workflow works correctly. Alternatively, I can modify the workflow to use `gr2m/create-or-update-pull-request-action@1`, which is allowed in the repository.

edit: It works correctly https://github.com/bjohansebas/expressjs.com-fork/pull/4

**Comment by crandmck** [comment]
Fixed by https://github.com/expressjs/expressjs.com/pull/1559
