### ISSUE TITLE
Remove runkit tool from the hello world page

### ISSUE THREAD

**Issue by bjohansebas** [expressjs/expressjs.com#1625]
It could be interesting if the page allowed you to run an Express server and test it directly, but we're using Runkit and it seems to always use Node 10

![image](https://github.com/user-attachments/assets/7ab34bb0-fd59-49c9-b9c4-12c4748bbf2b)

Since Express 5 requires Node.js 18, I think it's time to remove this tool as it can cause confusion in some cases due to the Node.js version (@expressjs/express-tc)

**Comment by crandmck** [comment]
I believe you can pick the Node version from the dropdown, incl v 18:
<img width="573" alt="Screenshot 2024-09-29 at 10 51 41 AM" src="https://github.com/user-attachments/assets/7bc8f77c-3a0e-4db0-bcaa-1ce4dc5b554d">

Instead of removing it altogether, perhaps just say to set the required min version for the desired Express version...?

**Comment by crandmck** [comment]
OK based on https://github.com/expressjs/expressjs.com/issues/1632 it seems it's not working at all, so yes let's get rid of it.
