### ISSUE TITLE
Reword router.VERB

### ISSUE THREAD

**Issue by Fishrock123** [expressjs/expressjs.com#239]
I think tj wrote them as that, but everyone knows them as "Methods".

We should either refer to them as `router.METHOD` or `router.{method}`.

**Comment by crandmck** [comment]
Yes, I agree that "method" is more standard terminology.  Since the term "verb" in this context is used all over in the docs, this will need to be a global fix to remain consistent.  I'd also add to the Glossary (with a mention of old/deprecated "VERB" terminology).

Also, I think the API reference ( http://expressjs.com/4x/api.html#router.VERB and http://expressjs.com/4x/api.html#app.VERB) should be very clear and explicit and actually list all the HTTP methods:
- GET
- HEAD
- POST 
- PUT
- DELETE
- TRACE
- OPTIONS
- CONNECT
- PATCH

Although this might seem like overkill, it could potentially be useful, for example, if someone is working on some existing code and wants to look up a call like app.put(...).  Right now, if you searched for that, you wouldn't find it in the docs.  I'd suggest only providing the explicit list of methods in the API docs, and noting that _METHOD_ represents any of them, then use that 'variable' elsewhere.  In general, my feeling is that docs should be specific and explicit when they can be.

Also, [Hage's book](https://www.packtpub.com/books/content/understanding-express-routes) says  that Express supports M-SEARCH, NOTIFY, SUBSCRIBE, and UNSUBSCRIBE methods that are not part of the W3C standard.  If that's true, we should state that.  Are there any other supported non-standard methods?

**Comment by Fishrock123** [comment]
> actually list all the HTTP methods

Um, node supports like 20+ methods just saying. XD

**Comment by crandmck** [comment]
OK--do you have a link to the Node docs that lists the supported methods? 

And Does Express support all the methods that Node supports?  I'm assuming the answer is "yes."  Are there any caveats?  In any case the docs should either list them all or (perhaps better) link to the relevant Node doc.  Otherwise, the reader is left to assume--and we all know what happens when you "assume."  
:-)

**Comment by jordonias** [comment]
Node supported methods can be found at https://github.com/joyent/node/blob/857975d5e7e0d7bf38577db0478d9e5ede79922e/tools/wrk/src/http_parser.h#L78-L110

I couldn't find anything in the node docs.

**Comment by dougwilson** [comment]
This is the specific list we use: https://github.com/jshttp/methods/blob/master/index.js#L13 ; all of those become methods on express.

**Comment by crandmck** [comment]
Thanks @dougwilson - I'll use that as the definitive list.  As far as I can tell, it does look the same as the Node list.  I think it's worth listing for completeness and specificity.

**Comment by dougwilson** [comment]
Yea, it should be the same, but the list was not added to node.js core until 0.11.something, so for all stable purpose, the list directly from `methods` is used (0.8 and 0.10).

**Comment by hacksparrow** [comment]
Updated - http://expressjs.com/4x/api.html#app.METHOD
