### ISSUE TITLE
Double callback invocation when `done` throws

### ISSUE THREAD

**Issue by bajtos** [expressjs/expressjs.com#270]
Consider the following example of a unit-test running `express().handle`:

``` js
var assert = require('assert');

var app = require('express')();
app.use(function(req, res, next) { next(); });

var req = { url: '/', verb: 'GET' };
var res = { setHeader: function(){} };
app.handle(req, res, function(err) {
  console.log('done', err && err.name + ' ' + err.message || 'ok');
  // simulate a failing test
  if (!err) assert(false);
});
```

Actual output:

```
$ node bug.js
done ok
done AssertionError false == true
```

Expected output:

```
$ node bug.js
done ok

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at bug.js:10:13
    (etc.)
```

I am not sure if there is a real-world scenario where the `done` callback throws an error, or whether this issue affects unit tests only.

To make it even more confusing,  the script behaves as expected and crashes with an unhandled error when there is no middleware registered in the app (i.e. `app.lazyrouter` was not called).

**Comment by dougwilson** [comment]
I think you meant to post this over in the `express` repo :)

**Comment by dougwilson** [comment]
Anyway, my answer would be that we shouldn't be calling the `done` callback within a `try` block, since I think pretty much anywhere in Node.js, once you're back in your callback, exceptions are you own problem :)

**Comment by dougwilson** [comment]
P.S. I highly suggest you not try to mock `req` and `res` at all, because next thing you know, the internals could start to call a method or access a property that always exists on normal `req` and `res` objects and then your tests will start to fail since they didn't happen to mock those. Wrapping `app` in `http.createServer` and using `superagent` is the typically-recommended method to test anything going through express.

**Comment by dougwilson** [comment]
This is fixed in express 3.18.3 and 4.10.2

**Comment by bajtos** [comment]
> This is fixed in express 3.18.3 and 4.10.2

Thank you Doug!

> P.S. I highly suggest you not try to mock req and res at all, because next thing you know, the internals could start to call a method or access a property that always exists on normal req and res objects and then your tests will start to fail since they didn't happen to mock those. Wrapping app in http.createServer and using superagent is the typically-recommended method to test anything going through express.

I agree, we use supertest in almost all of our tests. However, in the case of tests verifying router tweaks, I felt that calling the handle function directly was a better approach. One of the reasons is that express does the same - see [test/Router.js](https://github.com/strongloop/express/blob/ac56cf46063e461fbaf53c2c869a1a657e8adbe1/test/Router.js).

**Comment by dougwilson** [comment]
> One of the reasons is that express does the same - see test/Router.js.

Yes, but it shouldn't :) I was just trying to help you out. I've already removed the use of mocks in connect 3, because the tests broke one day when a dependency slightly changed and starting using a property I wasn't mocking. And for express, I'm actively removing all mocks from express's tests as they move to https://github.com/pillarjs/router/tree/master/test (files prefixed with `express.` are un-migrated files). TL;DR soon you'll be the only one mocking, which will make changes within express that break mocking less apparent to me.

**Comment by bajtos** [comment]
I see. In that case, I will rework my tests to use supertest too. Thank you for being patient with me :)

**Comment by dougwilson** [comment]
> Thank you for being patient with me :)

It's no problem :) I just want to make sure we're moving in the best direction :D What stinks a bit is when there is old things like those mock stuff in the tests, and I don't blame anyone for looking at them and saying "they do it that way, so should I!" lol.
