### ISSUE TITLE
Add a “Handling File Uploads” guide?

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#361]
@jakerella asked this:

> The Express 4.x docs don't seem to mention using file uploads, but the Express 3.x docs do. Had a question from a student in training and I said "oh, it's just on req.files" ...  only, it's not any more, apparently.

AFAIK, it's no longer in the Express docs because it comes from [multer](https://www.npmjs.com/package/multer) middleware, which is no longer "built-in" to Express.  See http://expressjs.com/guide/using-middleware.html#middleware.built-in.  Previously it was in body-parser, but it gave up on files (multipart) due to the complexities involved. `req.files` is now made available with multer.  The fact is covered in the Express 4 migration guide.

In discussion with @hacksparrow we were wondering if it merits specific mention somewhere, either as its own topic, or as part of an existing topic.  Does this seem like a FAQ or something worth highlighting?

**Comment by dougwilson** [comment]
Just in general, it didn't "give up" on multipart, only that parsing an entire multipart form up-front is a giant DoS attack risk due to the size of these forms. The only valid way to do multipart parsing is to either drop all files in the forms or use `multiparty`, `busboy` etc. directly in your route.

**Comment by jakerella** [comment]
FYI, I believe it needs to be mentioned in the documentation for two reasons:
1. because next to simple url encoded post bodies, it is the most common form encoding type and people use it in just about every web application; and
2. it _is_ mentioned in the 3.x docs since it was included in the body parser... in other words, I'd like some consistency in the API docs on major version upgrades.

Yes, I know that it mentions this in the migration docs from 3 to 4, but for someone new to Express it seems like an oversight. Honestly, just mentioning multi-part data somewhere and the fact that you need to use some other middleware (with an example of one) should be sufficient.

**Comment by crandmck** [comment]
Seems reasonable to me.  @hacksparrow could you please take a stab at it?  I think just a mention and link is sufficient.

**Comment by hacksparrow** [comment]
Added - http://expressjs.com/4x/api.html#req.

**Comment by jakerella** [comment]
:+1:

**Comment by crandmck** [comment]
LGTM. Thanks @hacksparrow

**Comment by dougwilson** [comment]
Please add `formidable`, `multiparty`, and `connect-multiparty`.

**Comment by dougwilson** [comment]
And `pez`.

**Comment by jakerella** [comment]
![Pez](https://s-media-cache-ak0.pinimg.com/236x/1d/b1/78/1db17803ac70f98bd10959b47339497f.jpg)

**Comment by hacksparrow** [comment]
Sorry, I missed this discussion somehow. Added all of the suggestions - http://expressjs.com/4x/api.html#req.
