### ISSUE TITLE
router.param() regex validation

### ISSUE THREAD

**Issue by sean3z** [expressjs/expressjs.com#388]
The express 4x api docs claim that you can pass regex as a second argument to [`router.param`](http://expressjs.com/4x/api.html#router.param) in order validate params.

> The method could now be used to effectively validate parameters (and
> optionally parse them to provide capture groups)

It then provides the following examples.

``` js
// validation rule for id: should be one or more digits
router.param('id', /^\d+$/);

router.get('/user/:id', function(req, res) {
  res.send('user ' + req.params.id);
});

// validation rule for range: should start with one more alphanumeric characters, followed by two dots, and end with one more alphanumeric characters
router.param('range', /^(\w+)\.\.(\w+)?$/);

router.get('/range/:range', function(req, res) {
  var range = req.params.range;
  res.send('from ' + range[1] + ' to ' + range[2]);
});
```

But, this doesn't actually seem to work. Taking a deeper dive, it doesn't look as if the [code](https://github.com/strongloop/express/blob/4.x/lib/router/index.js#L84-L114) actually supports what the docs claim. In fact, passing anything other than a function will get you a tidy `invalid param() call` exception.
#### Using

express `4.12.3`
node `0.12.4`

**Comment by kodypeterson** [comment]
I think you are going to have to use https://github.com/expressjs/express-params. I think the docs, that you copied, are just showing that you can use it and how.

"For example the express-params defines the following callback which allows you to restrict parameters to a given regular expression."

The docs could probably be worded a bit better to make that more clear.

**Comment by dougwilson** [comment]
The docs show, right above that example, that you actually have to run this code first; the example is simply split into two different code blocks and it won't work if you only use one of the two code blocks.

``` js
router.param(function(name, fn) {
  if (fn instanceof RegExp) {
    return function(req, res, next, val) {
      var captures;
      if (captures = fn.exec(String(val))) {
        req.params[name] = captures;
        next();
      } else {
        next('route');
      }
    }
  }
});
```

@hacksparrow how can that section be made clearer? It seems like this is always a large source of questions/confusion, because people are not reading it though and realizing they need to include that `router.param(function(name, fn) {` bit of code for it to work.

**Comment by sean3z** [comment]
Thanks guys, having that bit more clear would certainly be helpful! I would imagine it's pretty common to skim docs on how to consume an api rather than reading every line; albeit, I probably [sh|c]ould have read more in depth in this case.

**Comment by kodypeterson** [comment]
@dougwilson - Isn't that what express-params does? It seems it might be best to recommend that method as it seems the better way from a maintenance perspective for a consumer, right? Just some thoughts!

**Comment by sean3z** [comment]
@kodypeterson After some research, it doesn't seem as if express-params is needed. Doug actually provides an [example](https://github.com/strongloop/express/issues/2429#issuecomment-69940675) of how to accomplish, what I assume most people are trying to accomplish the `app.params(fn)` example from the doc. I believe this is why it was deprecated in the first place.

``` js
app.get('/user/:userId([0-9]+)', fn);
```

@dougwilson perhaps this (post `4.11`) example could be included in the docs (alongside the older example) to help avoid some of the confusion

**Comment by dougwilson** [comment]
Hi @kodypeterson the purpose of the section of the docs is to explain what `app.param(function)` does through examples; suggesting `express-params` module will not help anyone understand how to use `app.param(function)`.

@sean3z it is, right in the section labeled "The code in the next section can be migrated using the following, without the use of router.param(callback):". Erasing everything and only keeping that _will still not help people understand how to use `app.param(function)` signature, though_.

**Comment by dougwilson** [comment]
@kodypeterson we in fact do mention the `express-params` module right there in the docs being discussed already.

**Comment by dougwilson** [comment]
If it helps the discussion, instead of assuming the section is being read, I'm going to paste what is currently on the Express website right now. Please, everyone, we need help trying to make the section better explain how `router.param(callback)` works, so please provide suggestions to that section that will help (either here, or even a PR!).

> router.param([name,] callback)
> 
> Add callback triggers to route parameters, where name is the name of the parameter or an array of them, and function is the callback function. The parameters of the callback function are the request object, the response object, the next middleware, and the value of the parameter, in that order.
> 
> For example, when :user is present in a route path, you may map user loading logic to automatically provide req.user to the route, or perform validations on the parameter input.
> 
> ```
>    router.param('user', function(req, res, next, id) {
>      // try to get the user details from the User model and attach it to the request object
>      User.find(id, function(err, user) {
>        if (err) {
>          next(err);
>        } else if (user) {
>          req.user = user;
>          next();
>        } else {
>          next(new Error('failed to load user'));
>        }
>      });
>    });
> ```
> 
> Param callback functions are local to the router on which they are defined. They are not inherited by mounted apps or routers. Hence, param callbacks defined on router will be triggered only by route parameters defined on router routes.
> 
> A param callback will be called only once in a request-response cycle, even if the parameter is matched in multiple routes, as shown in the following example.
> 
> ```
> router.param('id', function (req, res, next, id) {
>   console.log('CALLED ONLY ONCE');
>   next();
> })
> 
> router.get('/user/:id', function (req, res, next) {
>   console.log('although this matches');
>   next();
> });
> 
> router.get('/user/:id', function (req, res) {
>   console.log('and this matches too');
>   res.end();
> });
> ```
> 
> router.param(callback) is deprecated as of v4.11.0.
> 
> By passing only a callback function, you can alter the router.param() API. For example the express-params defines the following callback which allows you to restrict parameters to a given regular expression.
> 
> The code in the next section can be migrated using the following, without the use of router.param(callback):
> 
> ```
> router.get('/user/:id([0-9]+)', function(req, res){
>   res.send('user ' + req.params.id);
> });
> 
> router.get('/range/:range(\\w+\.\.\\w+)', function(req, res){
>   var range = req.params.range.split('..');
>   res.send('from ' + range[0] + ' to ' + range[1]);
> });
> 
> router.param(function(name, fn) {
>   if (fn instanceof RegExp) {
>     return function(req, res, next, val) {
>       var captures;
>       if (captures = fn.exec(String(val))) {
>         req.params[name] = captures;
>         next();
>       } else {
>         next('route');
>       }
>     }
>   }
> });
> ```
> 
> The method could now be used to effectively validate parameters (and optionally parse them to provide capture groups):
> 
> ```
> // validation rule for id: should be one or more digits
> router.param('id', /^\d+$/);
> 
> router.get('/user/:id', function(req, res) {
>   res.send('user ' + req.params.id);
> });
> 
> // validation rule for range: should start with one more alphanumeric characters, followed by two dots, and end with one more alphanumeric characters
> router.param('range', /^(\w+)\.\.(\w+)?$/);
> 
> router.get('/range/:range', function(req, res) {
>   var range = req.params.range;
>   res.send('from ' + range[1] + ' to ' + range[2]);
> });
> ```
> 
> The router.use() method also supports named parameters so that your mount points for other routers can benefit from preloading using named parameters.

**Comment by hacksparrow** [comment]
@dougwilson @sean3z @kodypeterson 

I agree, that section can be pretty confusing, especially with a notice box with some code in it and a reference to an external module. Let's make it as simple as possible, while still conveying the message clearly. Here is the re-write I am proposing. Everything after "router.param(callback) is deprecated as of v4.11.0." will be replace with the following.

The behavior of the `router.param(name, callback)` method can be altered entirely by passing only a function to `router.param()`. This function is a custom implementation of how `router.param(name, callback)` should behave - it accepts two parameters and must return a middleware.

The first parameter of this function is the name of the URL parameter that should be captured, second parameter can be any JavaScript object which might be used for returning the middleware implementation.

The middleware returned by the function decides the behavior of what happens when a URL parameter is captured.

In this example, the `router.param(name, callback)` signature is modified to `router.param(name, accessId)`. Instead of accepting a name and callback, `router.param()` will now accept a name and a number.

```
var express = require('express');
var app = express();
var router = express.Router();

// customizing the behavior of router.param()
router.param(function(param, option) {
  return function (req, res, next, val) {
    if (val == option) {
      next();
    }
    else {
      res.sendStatus(403);
    }
  }
});

// using the customized router.param()
router.param('id', 1337);

// route to trigger the capture
router.get('/user/:id', function (req, res) {
  res.send('OK');
})

app.use(router);

app.listen(3000, function () {
  console.log('Ready');
})
```

In this example, the `router.param(name, callback)` signature remains the same, but instead of a middleware callback, a custom data type checking function has been defined to validate the data type of the user id.

```
router.param(function(param, validator) {
  return function (req, res, next, val) {
    if (validator(val)) {
      next();
    }
    else {
      res.sendStatus(403);
    }
  }
})

router.param('id', function (candidate) {
  return !isNaN(parseFloat(candidate)) && isFinite(candidate);
});
```

**Comment by dougwilson** [comment]
SGTM

**Comment by hacksparrow** [comment]
Published. Please close the issue if it looks good.

**Comment by sean3z** [comment]
This looks much better and should help mitigate some of the confusion!

Thanks for the quick turn around and assistance!

**Comment by hacksparrow** [comment]
👍
