### ISSUE TITLE
`req.fresh` and `req.stale`

### ISSUE THREAD

**Issue by ForbesLindesay** [expressjs/expressjs.com#39]
It's really not clear what these do?  Where are they getting `Last-Modified` from to compare?

**Comment by tj** [comment]
from the response header field, I'll add some real examples tonight haha. basically you'd set the etag etc as you normally would and do `if (req.fresh) res.status(304)`, it's not really something you'd need to even touch for most cases since `res.send()` does all that

**Comment by ForbesLindesay** [comment]
I was wondering if it might be intended to help with sending 304's for more dynamic pages.  e.g. for applications with lots of read activity and only a little write activity, you might want to maintain a 'last updated' field in memory at some granularity level, then you could send 304's if that hadn't changed, without making db queries.

**Comment by tj** [comment]
yeah if you had "hot" content you could potentially circumvent a lot of the processing with custom 304 handling, the res.send() portion is still a win since you're not transferring a bunch of data but it's definitely preferred to optimize where applicable. we could probably add a nicer api on top of this stuff for that

**Comment by tciuro** [comment]
It would be good to have a request/response example that illustrates how to implement ETag support. Thanks!
