### ISSUE TITLE
Confusing documentation around response.end([data])

### ISSUE THREAD

**Issue by b-long** [expressjs/expressjs.com#392]
I'm sure many people aren't confused by this, but I was so perhaps others are too.  I'm new to express so bear with me.  In reading the [guide to using middleware](http://expressjs.com/guide/using-middleware.html), I see usage of `res.end([data])`.  I initially thought `end` didn't support arguments, so I quickly go over to the [`res.end`](http://expressjs.com/4x/api.html#res.end) API docs.  The documentation for this function seems to correctly identify the arguments, but it says "_Use to quickly end the response without any data. If you need to respond with data, instead use methods such as res.send() and res.json()._" .  So, what's the deal with the `end` API?  Is it changing?  Is `data` being deprecated?

**Comment by dougwilson** [comment]
The `res.end` actually comes from Node.js itself. It's documentation can be found at https://nodejs.org/api/http.html#http_response_end_data_encoding_callback

As for deprecating anything, that would be up to Node.js.

Our documentation links to that of Node.js, but even though it exists at the will of Node.js, we still discourage it for use for sending data, which is why we put that note in our own documentation. Any suggestions about clearning this up for your point of view is most welcome!

**Comment by b-long** [comment]
Ah, thanks so much @dougwilson ! :+1: 

I think in reading [`res.end`](http://expressjs.com/4x/api.html#res.end)'s API documentation, I somehow glossed over that.  Perhaps re-wording it the way you've stated here ("_`res.end` actually comes from Node.js itself_") would be more helpful to Express newcomers, but other readers might not gloss over the way it's currently written as I did :smiley:

**Comment by crandmck** [comment]
The link in our doc wasn't quite right, so I fixed that and tried to improve the wording: 
http://expressjs.com/4x/api.html#res.end.

Does that clarify?

**Comment by b-long** [comment]
Yes, I think that's much better :smile:   I'll close this issue if you're alright with it.  Thanks again!

**Comment by crandmck** [comment]
Thank _you_ for helping to improve the docs!
