### ISSUE TITLE
Fix req.body example

### ISSUE THREAD

**Issue by ritch** [expressjs/expressjs.com#449]
http://expressjs.com/api.html#req.body

We should be able to remove the `multer` reference... I think this was a copy/replace error. Or we need to fix the usage. `multer` has a set of methods like `multer.single('avatar')` to populate `req.file` and similar.

@crandmck @hacksparrow

**Comment by ritch** [comment]
Also see: https://github.com/strongloop/express/issues/2762

**Comment by dougwilson** [comment]
Looks like the issue is not with our docs--they were fine, but what happened was `multer` released a 1.0.0 with breaking changes. You can see the old docs (https://github.com/expressjs/multer/tree/7f6d840bd3a3ce6b4d81b1fb230e999880cc8438#usage) shows `app.use(multer())` which works if you install the pre-1.0 versions.

I think the documentation should make it clear what version of third-party module are being used in the examples when we provide them, so that this doesn't keep popping up :)

**Comment by hacksparrow** [comment]
Updated the example and indicated the `multer` version in a comment.

**Comment by silenceisgolden** [comment]
Since the other issue was closed without a response? @ritch 

```
let fd = new FormData(document.querySelector('form'));
let xhr = new XMLHttpRequest();
xhr.open('POST','https://www.somewhere.com/url', true);
xhr.send(fd);
```

This results in a multipart/form-data request to the endpoint that might be setup with express (without a way to change the encoding type from my research), so I would say an example needs to be made for this use case. This is how to deal with it though:

```
let multer = require('multer');
let formDataMiddleware = multer();

app.post('/url', formDataMiddleware.array(), (req, res) => {
  console.log(req.body); // req.body is populated with form inputs
});
```

Edited: Made xhr async, so no deprecation notice.

**Comment by hacksparrow** [comment]
@silenceisgolden the example has already been updated. Please take a look - http://expressjs.com/4x/api.html#req.body.

**Comment by silenceisgolden** [comment]
Looks good, thanks
