### ISSUE TITLE
Update examples and docs for ES 6

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#470]
All current docs and examples are written in ECMAScript 5.  We would like to stay current and provide docs and examples that use the latest ES 6 features.

**Comment by hacksparrow** [comment]
@dougwilson what's your opinion about this?

**Comment by dougwilson** [comment]
Seems OK, since people can write in whatever they like to actually use Express :) I can say that at least in corporate environments, there is virtually no ES6 knowledge, so if the examples were only ES6 it would probably confuse some percentage of our user base. Everything that can run ES6 runs ES5, so there isn't a big move to it in aware of (I'm mainly talking about all the new sugar syntax like const, let, class, etc.).

**Comment by crandmck** [comment]
FYI this was suggested by @ritch.  I would think that the devil is in the details....  We certainly don't want to confuse anyone, but if there are cases where you can do things more efficiently with ES6, then we should provide an example and explanation.  This might actually take quite a bit of time and effort to do properly, so will need to work on according to priority.

**Comment by ritch** [comment]
> I can say that at least in corporate environments, there is virtually no ES6 knowledge

I think we can help change that.

**Comment by listepo** [comment]
You can now start rewrite on es6 (babel)
