### ISSUE TITLE
Create documentation in gitbook to download

### ISSUE THREAD

**Issue by gilsondev** [expressjs/expressjs.com#566]

**Comment by crandmck** [comment]
I don't know anything about GitBook, but it looks interesting. I assume the purpose of this is to create a PDF, since the HTML/web version already exists :-)

Let me look into it a bit more to see what's involved.  Are there are any specific suggestions?

Anyone else interested in this suggestion?

**Comment by crandmck** [comment]
Hi @gilsondev Thanks for the suggestion.

I tried it out, and unfortunately it looks like it wouldn't be easy to generate a GitBook from this repo since its structured to use Jekyll.  

Here are some of the issues I encountered:
- YAML preface in each page is necessary for Jekyll and translation and I couldn't find a way to make GitBook ignore it; for example:

```
---
### TRANSLATION INSTRUCTIONS FOR THIS SECTION:
### TRANSLATE THE VALUE OF THE title ATTRIBUTE AND UPDATE THE VALUE OF THE lang ATTRIBUTE.
### DO NOT CHANGE ANY OTHER TEXT.
layout: page
title: Express application generator
menu: starter
lang: en
redirect_from: "/starter/generator.html"
### END HEADER BLOCK - BEGIN GENERAL TRANSLATION
---
```
- Intrasite links contain a liquid template variable to ensure the link works in all languages, e.g.:
  `...if you use the [Express generator](/{{ page.lang }}/starter/generator.html), which creates the scaffolding...`  DocBook can't handle the `{{ page.lang }}` part.

There may be other roadblocks, but those are the first two I encountered.  Do you have any suggestions as to how to resolve them?  I'm hesitant to proceed if not.

I would certainly be possible to fork the repo, modify the content as necessary, and create a GitBook from that--but it would eventually diverge from this repo, so it would just be a "snapshot" and would entail a fair amount of work each time.  If you're interested in doing that, please feel free.

For my "quickie" POC repo, see https://github.com/crandmck/expressjs.com.

**Comment by gilsondev** [comment]
I understand. The structure created for this leaves more complicated to use in gitbook. In this case it would follow the structure that it suggests he can adapt to online reading and download :/

Initially would be the site for documentation and adaptation gitbook, ie two jobs. I do not have in mind as we could automate this

**Comment by crandmck** [comment]
I'm going to go ahead and close this, but will be happy to revisit if there is way to address the issues I noted above.
