### ISSUE TITLE
Improve documentation of app.use() mounting sub-applications

### ISSUE THREAD

**Issue by tunniclm** [expressjs/expressjs.com#567]
While looking at https://github.com/strongloop/express/issues/2865 I noticed that the inheritance of application settings (particularly in relation to defaults) does not appear to be documented either in the `app.use()` or `Event: mount` sections.

It would be good to amend the documentation to describe some of the information in that issue, particularly Doug's comment (which is more readable than some of the earlier ones I made):
https://github.com/strongloop/express/issues/2865#issuecomment-176914119

**Comment by crandmck** [comment]
Makes sense.  Let me look into it.

**Comment by crandmck** [comment]
@tunniclm app settings are documented in http://expressjs.com/en/4x/api.html#app.settings.table. 

IIUC, a sub-app will inherit the value of an app setting, _unless_ the app setting has a default value.  All of the settings in that table have default values, except for `view engine`, so we should just state along with that table that a sub-app will inherit the value of `view engine` and any other "custom" setting you define that does not have a default value.  Is that right?

Now that I look at it, default for `view cache` is listed as "true in production."  But what about otherwise--Is it false by default or does it not have a default value?  And default for `json replacer` is null -- is that the same as not having a default or not?

**Comment by tunniclm** [comment]
Just checked the (v4.13.3) code and 'view cache' is not set unless env is production, so no default otherwise.

Properties with default settings: x-powered-by, etag, env, query parser, subdomain offset, trust proxy*, view, views, jsonp callback name, view cache**

\* As mentioned, trust proxy does inherit because it has been explicitly coded to do so for back-compatibility.
*\* As you said, view cache is only set as a default when env is production

I would say we want to add a little section in the `app.use()` and/or `Event: mount` doc that describes that sub apps inherit app settings from the parent that do not have a default option (maybe link/refer to the app settings table as well).

**Comment by crandmck** [comment]
See the PR. 
@tunniclm  I added an explanation of when settings are inherited in the sections you suggested with xref.
I also tried to clarify the settings table and made a few other unrelated formatting changes here and there.

**Comment by crandmck** [comment]
This is done.
