### ISSUE TITLE
http://expressjs.com/ lacking a favicon.

### ISSUE THREAD

**Issue by Eddy1028** [expressjs/expressjs.com#607]
Hi,
When I visit http://expressjs.com/ , it makes me feel uncomfortable/unprofessional without a favicon on this site.
I hope you'll add it soon, then I will be happy :)

![image](https://cloud.githubusercontent.com/assets/6291736/13953100/1bf1675c-f075-11e5-9818-20270405b349.png)

**Comment by dougwilson** [comment]
Express doesn't have a logo to even make a favicon from. The logo you highlighted in your screenshot is the logo for Strongloop. I think that logo appearing next to the word "Express" is actually an error on the website.

**Comment by crandmck** [comment]
> I think that logo appearing next to the word "Express" is actually an error on the website.

Yes @dougwilson that was an oversight.  I just removed it with 241a27a9fe6afedcc3afb2f90d1a519cbcab08a4. 
It was in CSS, so to see the change, you might have to do a hard-refresh to clear your browser cache.

I agree it would be nice to have a favicon, but as Doug notes, we don't have a logo.  Perhaps we can come up with a simple logo for this purpose?   I presume the TC would have to sign off on it.  Anyone have a suggestion?

**Comment by crandmck** [comment]
I just thought of something - what about using the default favicon set by the Express generator from `serve-favicon`:  ![express-favico](https://cloud.githubusercontent.com/assets/2925364/13995496/a68673be-f0e6-11e5-9bf8-d4aee68d09ed.png) ?

Where did that image come from?  Can we use it?

It might give people the idea that the site uses Express itself (which it doesn't), so that's a counter-argument.  But maybe it would be better than no favicon?

**Comment by hacksparrow** [comment]
That's the [connect](https://github.com/senchalabs/connect) icon, if I am not mistaken.

**Comment by crandmck** [comment]
OK, then maybe not such a great idea :-(

If that's true, then it begs the question of whether it's the best favicon to use for the `express` generator and `serve-favicon`.

**Comment by dougwilson** [comment]
The express generator provides no icon at all (https://github.com/expressjs/generator/blob/master/templates/js/app.js#L17-18). I would assume that is from the Express generator for the 3.x line of Express, which was based on Connect. I wouldn't use that icon here, because it's likely that Sencha Labs owns the copyright on that icon.

**Comment by crandmck** [comment]
Interesting.  I wonder why I see it?  Perhaps I'm doing something wrong or misunderstanding.

Here's how I got the above screenshot of the favicon:
- Updated my installation of the generator: `npm i -g express-generator` (running `express --version` shows 4.13.1).
- Created a new app, with `express my-express-app` & installed deps with `npm i`
- Ran with `npm start`
- Loaded http://localhost:3000/.  The [above icon](#issuecomment-200468934) was shown in the browser tab.

I can see that the generated `app.js` has this line:
`var favicon = require('serve-favicon');`
But this line is commented out:
`//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));`

So I don't understand where it's coming from....?  Does the browser cache it or something? 

>  I wouldn't use that icon here, because it's likely that Sencha Labs owns the copyright on that icon.

OK, so I guess it's moot anyway, but I'm still curious about ^.

**Comment by dougwilson** [comment]
I'm sure your browser has it cached. Try clearing your entire browser cache or even using a completely different browser. If you ever loaded something on localhost port 4000 with that icon, it would get stuck there for any site on that host.

**Comment by dougwilson** [comment]
Another trick to update the cache is to manually browse to the favicon file, http://localhost:4000/favicon.ico let it 404 and then go back to the page and reload.

**Comment by crandmck** [comment]
> I'm sure your browser has it cached.

Yep, that was it.  I used a different browser and it didn't show up.   Thanks for clearing that up!

Now we're back to the original issue:

> ...it makes me feel uncomfortable/unprofessional without a favicon on this site.

I think it would be worthwhile to address this at some point.  It's not urgent, though, since there has not been a favicon (at least since I've been involved with the project ~18 months +).

**Comment by hacksparrow** [comment]
https://github.com/strongloop/expressjs.com/commit/a74564bdbe3066dcb4b9214a32689c6a9b96d45f adds an "interim" favicon. We continue to work on the logo in the meantime.

**Comment by crandmck** [comment]
Thanks @hacksparrow ... Good start.  Definitely better than nothing!
