### ISSUE TITLE
Does express router supports matrix patameters like jax-rs framework.

### ISSUE THREAD

**Issue by atulatgithub** [expressjs/expressjs.com#648]
Hello Express Team,
Does express router supports parasing matrix patameters like jax-rs framework.

example :
/books/2011;author=mkyong
here authoer-mkyong is called as matrix parameter.
Can I natively parsed this in Express.js

Jax-rs framerork url
http://www.mkyong.com/webservices/jax-rs/jax-rs-matrixparam-example/

**Comment by atulatgithub** [comment]
@kevinburkeshyp
@davidyang

**Comment by hacksparrow** [comment]
What's the problem with using the standard `/books/2011?author=mkyong`?

**Comment by hacksparrow** [comment]
Express does not support that format. For queries about Express, join us at https://gitter.im/expressjs/express.

**Comment by atulatgithub** [comment]
Using matrix parameters is more suited to our Use Case.

No problem is using /books/2011?author=mkyong?

**Comment by hacksparrow** [comment]
You might find http://expressjs.com/en/4x/api.html#req.params useful.

**Comment by dougwilson** [comment]
Hi @atulatgithub, the support for matrix parameters in Express routing was only ever brought up one time before in https://github.com/expressjs/express/issues/2532 and it ended with the user never making a pull request to even get an implementation going (see https://github.com/expressjs/express/issues/2532#issuecomment-73341441). You're welcome to start one!

**Comment by duaraghav8** [comment]
@dougwilson 
I recently had to use matrix URIs at my internship. Seeing that there wasn't much support out there for Matrix URIs in Node, I've developed an npm module (matrix-parser) for this purpose.

Its fully functional (although not optimized, but I'm working on it). Since I'm not so experienced with JS, I'd appreciate if you could have a look at the module and give me feedback.

I've written lots of tests to cover side-cases, you can see their descriptions to understand what rules my module follows for parsing MU.

If you think that this is something you could use, please let me know. I'd like contribute to express as well :)

[Here's the repo](https://github.com/duaraghav8/matrix-parser)

**Comment by atulatgithub** [comment]
Hello Rahav,
Thanks for the efforst u have taken to implement this.
Will see in coming weekend. Right now I am really tied.

**Comment by duaraghav8** [comment]
Hi Atul,
Sure, let me know what you think:)
