### ISSUE TITLE
add express-database middleware

### ISSUE THREAD

**Issue by reklatsmasters** [expressjs/expressjs.com#689]
I developed [`express-database`](https://github.com/reklatsmasters/express-database) middleware for ease connecting to databases. Main features is auto - opening and auto - closing new connections.

**Comment by blakeembrey** [comment]
@ReklatsMasters What is the request/issue? Personally I don't think we should promote this pattern. Coupling a database connection to the request/response life cycle doesn't give any advantages and makes can make things quite difficult to use. It's not a pattern I would recommend personally. What do you think makes it a good pattern?

**Comment by reklatsmasters** [comment]
In a real life we need persistent database connection. Many sites has api. And for that api they need a database connection. Each user, each request to your api should have your own database connection. So I think it's a useful and convenient pattern. 

> What is the request/issue?

I'm about this page http://expressjs.com/en/resources/middleware.html

**Comment by blakeembrey** [comment]
I understand how "real life" works, but tying database connections to the request response cycle really doesn't give any benefit. For instance, if you're keeping a persistent connection then you're already creating issues for yourself. Most likely, the backing database has pooling built in instead and you'd be using that. All this does over the top of that is abstract the access to the underlying level away, which really isn't beneficial as a lot of database connectors don't have pooling, etc. built-in. 

Also, a lot of endpoints won't ever use a database connection. On top of that, what about long-running streaming endpoints? I'm just not seeing a valuable reason for this level of abstraction. Most likely it would cause problems for beginners down the line, and anyone else probably shouldn't use this sort of pattern to begin with - you should be working with some other abstraction instead of setting raw database querying on each request (E.g. have a model abstraction, some data validation, etc).

**Comment by blakeembrey** [comment]
Do you perhaps have an example of this pattern used in production?

**Comment by reklatsmasters** [comment]
Yes, i use in production some of that:

``` js
// main.js
const api = require('./api')
const app = express()
// static, cookies, body-parser here

app.use('/api', api)
app.get('/', (req, res) => res.render('index'))

// error handler at the end
```

``` js
// api.js

// connect to database
router.use(database({ db: mysql('mysql://foo:bar@example.com') }))

router.get('/users', (req, res, next) => {
    req.database.query('select * from company.users').then(rows => res.json(rows)).catch(next)
})
```

> the backing database has pooling built in instead and you'd be using that. 

Pooled connections isn't a problem. I think i can implement it but it's a next abstraction level. It's should be used in connectors for `express-database`.

> you should be working with some other abstraction instead of setting raw database querying on each request (E.g. have a model abstraction, some data validation, etc).

It's already implemented in some other libraries like knex, sequelize, etc.

> if you're keeping a persistent connection then you're already creating issues for yourself.

Which issues? I can't imagine.

**Comment by blakeembrey** [comment]
All your code does is wrap MySQL and set `req.database = mysqlConnection`. Since it's pooled behind that, there's no value gained from tying the database lifecycle to the request/response lifecycle. In any complex application, you will inevitably need to make database requests outside of the request/response cycle. Maybe you need to support long-running connections also, like a real-time stream. All of these require higher level abstractions, and it doesn't make sense to tie those abstractions to a request/response lifecycle.

> It's already implemented in some other libraries like knex, sequelize, etc.

Exactly. You should be using some other framework here if you want to build reasonably complex applications. You **do not** want to be writing raw SQL queries from within the request/response lifecycle. How would you ever refactor this? What if you starting moving away from REST and implement GraphQL/Falcor? What if you implement Websockets? You definitely do not want to tie the data access layer to the data delivery layer as the data delivery layer can, and probably will, change. You will need to refactor routes, implement security, etc.

> Which issues? I can't imagine.

Aside from the existing issues I've mentioned, it's putting too much pressure on the underlying database access layer. The only way the underlying access layer can scale is using a pooled connection. At which point, this coupling is irrelevant is because it's superficial and poor practice. For instance, if it wasn't pooled and someone found an endpoint that's slow at responding (E.g. there's some JSON input parsing going on, etc) and it's opening one connection per user it's going to have the connection idling for a long duration putting additional pressure on the database to maintain dozens of open connections not doing anything. A lot of databases (and DBaaS) are not designed to maintain potentially thousands of connections and usually have a limit.

**Comment by reklatsmasters** [comment]
I think you are right. :confused:  :disappointed:

**Comment by hacksparrow** [comment]
Closing this.
