### ISSUE TITLE
Documentation for Express version 4.5.1 update res-sendStatus.md

### ISSUE THREAD

**Issue by oxy-gendotmobi** [expressjs/expressjs.com#779]
This command does not seem to exist in Express version 4.5.1. 
It gives:
TypeError: res.sendStatus is not a function

Maybe this page should be edited that only version 4.x but not 4.5.1 and later???

File:
expressjs.com/_includes/api/en/4x/res-sendStatus.md

**Comment by hacksparrow** [comment]
@oxy-gendotmobi thanks for bringing this to notice.

@expressjs/express-tc I suggest adding a "Availability" label beside the API header to address this kind of issues. Currently we have included notice boxes for those APIs which users have "complained" about. A better solution is to label all the APIs to address all current and potential issues in future.

A mockup is included below.

![availability](https://cloud.githubusercontent.com/assets/950112/22619327/85925178-eb18-11e6-9e58-7438118fb9ab.png)

**Comment by dougwilson** [comment]
@oxy-gendotmobi your version is Express is too old, not too new :) `res.sendStatus` was not in Express until version 4.9.0, so if you upgrade to 4.9.0 or higher you'll be able to use that method.

@hacksparrow Yes, definitely a good idea. The mock up style itself LGTM, with a few comments:

1) For the arability, some of the forever-existing methods may be a long hunt to capture which version that they came to exist. I would say that perhaps the availability is only marked if the function came into existence sometime within the major version of Express the documentation is for (i.e. we only note that `res.sendStatus` came out in 4.9.0 and not note when `res.send` came to be in the 4.x docs since it was there the entire 4.x life time).
2) The deprecated we could add the version it became deprecated in, but at least noting it is better than nothing :)

**Comment by hacksparrow** [comment]
@dougwilson good suggestions!

@iamropo here's something you can work on.

@oxy-gendotmobi I will close this issue and open a new one to address availability/deprecation information.
