### ISSUE TITLE
res-sendStatus.md -> res.sendStatus(2000), here 2000 is invalid.

### ISSUE THREAD

**Issue by llwslc** [expressjs/expressjs.com#805]
node code:
https://github.com/nodejs/node/blob/e0a9ad1af244f8756a228a6d087b3a55ee4c0d14/lib/_http_server.js

```
if (statusCode < 100 || statusCode > 999)
    throw new RangeError(`Invalid status code: ${originalStatusCode}`);
```

**Comment by crandmck** [comment]
That does seem to imply that the [res.sendStatus](http://expressjs.com/en/4x/api.html#res.sendStatus) doc is incorrect, specifically:
> If an unsupported status code is specified, the HTTP status is still set to statusCode and the string version of the code is sent as the response body.
>
> `res.sendStatus(2000); // equivalent to res.status(2000).send('2000')`

@dougwilson Should this instead say that a status code  < 100 or > 999 will throw an error?

**Comment by dougwilson** [comment]
I believe the docs are correct, but I can see how someone thought that the 2000 was a typo for 200 (even through the docs are explaining it's showing an error). I would say maybe that spot should just show an obviously-bogus code instead of 2000, for example maybe 1234.

**Comment by dougwilson** [comment]
> Should this instead say that a status code < 100 or > 999 will throw an error?

And no, as we don't throw any errors. If you are using a version of Node.js that throws an error, it will throw at a later time, so if we want to document Node.js's behavior (besides that we note "the HTTP status is still set to statusCode") then we need to list which versions of Node.js throws and which ones do not (it's not an easy before and after a single version -- they backported it and so it starts and stops and starts and stops) so people understand which behavior they should be expecting. Personally I would defer to reading the docs for the Node.js version they are using, since that is simpler.

**Comment by llwslc** [comment]
node code log:
https://github.com/nodejs/node/commit/abd101be1a
node version log:
https://github.com/nodejs/node/blob/4897ae211423a6282cd7a258ede9358743784e6f/doc/changelogs/CHANGELOG_V5.md

so when node version > 5.11.0 (Stable), will throw an error as shown below.


![image](https://cloud.githubusercontent.com/assets/5865414/25795452/f5548624-3407-11e7-9fda-fb70c2290972.png)


![image](https://cloud.githubusercontent.com/assets/5865414/25795557/6c05f3ca-3408-11e7-9dcb-28ec981a0cd5.png)


```
const app = require('express')();

app.use(function (err, req, res, next) {
  // not work
  res.status(888).send('Something broke!')
})

app.get('/', function (req, res)
{
  res.sendStatus(2000)
});

app.listen(28888, function ()
{
  console.log(`Express started...`);
});
```

**Comment by dougwilson** [comment]
It is also thrown in some version of 4.x, but not all. If you are using a version of Node.js that throws an error, it will throw at a later time, so if we want to document Node.js's behavior (besides that we note "the HTTP status is still set to statusCode") then we need to list which versions of Node.js throws and which ones do not (it's not an easy before and after a single version -- they backported it and so it starts and stops and starts and stops) so people understand which behavior they should be expecting. Personally I would defer to reading the docs for the Node.js version they are using, since that is simpler.

**Comment by crandmck** [comment]
OK, I _think_ I understand what's going on... 

In general I agree with @dougwilson that we should not try to document Node behavior and instead refer to Node docs.

So, IIUC the upshot is we should say something like:

> Certain versions of Node.js will throw an error for status codes outside the 100 - 999 range.  For more information, see <link to Node docs> for the version of Node you're using.

Is that correct and would it be helpful?  What would be the link?

Also, changing "2000" to "1234" in the example might be a good idea to avoid any possible confusion, as Doug suggests.

**Comment by dougwilson** [comment]
@crandmck right. Because the title of this issue is "res-sendStatus.md -> res.sendStatus(2000), here 2000 is invalid" and the reason 2000 is used is because _it's trying to show something invalid_. I think that changing 2000 -> 1234 is likely the best way to resolve the initial misunderstanding.

In addition, we can tweak the description a bit. Currently it says:

> If an unsupported status code is specified, the HTTP status is still set to statusCode and the string version of the code is sent as the response body.

We could maybe tweak it to be something like the following:

> If an unsupported status code is specified, the HTTP status is still set to statusCode and the string version of the code is sent as the response body. Certain versions of Node.js will throw an error for status codes outside the 100 - 999 range. For more information, see for the version of Node you're using.

**Comment by llwslc** [comment]
Not only throw an error, but also the HTTP statusCode will set to 500 (see Figure 2).

**Comment by dougwilson** [comment]
@llwslc any error you throw within a handler ends up going through the error handling middleware. The fact that it comes through as a 500 is an implied behavior from the throw statement, it is not somehow specific to this `res.sendStatus` in any way. You can see this with the following:
```js
const app = require('express')();

app.use(function (err, req, res, next) {
  // not work
  res.status(888).send('Something broke!')
})

app.get('/', function (req, res)
{
  throw new Error('oh no!!');
});

app.listen(28888, function ()
{
  console.log(`Express started...`);
});
```
