### ISSUE TITLE
response incomplete json data

### ISSUE THREAD

**Issue by rickywu** [expressjs/expressjs.com#870]
The version info: "express": "~4.15.2", "express-session": "^1.15.5",

I use this code send large json data to client:

```
   router.get('/exportAllData',function(req,res,next){
    async function getData(){
    let sql="SELECT * FROM int_information "
    let rows=await query(sql);
    let data=await JSON.stringify(rows);
    return JSON.parse(data);
  }
  getData().then(data=>res.send({flag:1,data:data})).catch(error=>{
    res.send({flag:0,err:error});
  });  
})
```
I tried wget localhost on server and can get full data, But the remote client got broken json data and different each time refresh. Where is the problem? Seems response closed before get all data.

**Comment by crandmck** [comment]
I don't think this is a doc issue...?

If I'm right, then we should move it to express repo, if it's a valid issue.  @dougwilson LMK.

**Comment by dougwilson** [comment]
Yea, it's not a doc issue, but if the user is using Node.js 8.x, they are describing an open Node.js bug that was introduced in 8.0.0

**Comment by rickywu** [comment]
Sorry opned in the wrong place, but where is the open bug, could you send me a link?

**Comment by dougwilson** [comment]
There are quite a few, with some say fixed, some not. I'm also not clear what fixes were atrempted when. Here is one that also includes a lot of links to others at the bottom: https://github.com/nodejs/node/issues/13391

If you're still not sure, please feel free to file a new issue in the main Express repo as well and we can help you validate if it is an Express issue or Node.js issue. But if downgrading to 6.x or 7.x fixes it, I'm 100% sure you are seeing the Node.js 8.x timeout bug, because it manifests exactly as you described.

**Comment by rickywu** [comment]
I revert back to node 7.10.1 and solved this problem, this issue should be closed.
Thank you so much.

This issue still happen in node js 8.7.0

**Comment by brice751** [comment]
I know it now



https://quagmire54.github.io/marketer/
