### ISSUE TITLE
document translation

### ISSUE THREAD

**Issue by BaroqueCoding** [expressjs/expressjs.com#875]
I just started to contribute open-source project by translation.
It seems the 4.x API document(ko) remains untranslated.
If you agree with, I can translate into Korean.

**Comment by crandmck** [comment]
Hi @BaroqueCoding, thanks for the offer.   LoopBack 4 is still very much under development, and the docs are not ready for translation yet.   I wouldn't suggest starting on translation until after v4 GA, which will be some time next year (likely late Q1 or Q2, I suspect, but still TBD).

If you're interested, you could help translating v3 docs to ko, because there is a lot not yet translated.  For general instructions to contribute translations, please see http://loopback.io/doc/en/contrib/translation.html.

**Comment by crandmck** [comment]
Hi @BaroqueCoding Thanks for the offer.  
We haven't translated the [API documentation](http://expressjs.com/en/4x/api.html) into any languages.  The rest of the doc is translated, but not the API doc.

If you want to help update the Korean translation of other parts of the docs, that would be great. 
Just compare the date of the ko page to the corresponding en page, and if the en page has been modified more recently, the translation needs updating.  Compare the changes in the en page to see specifically what needs to be updated in the translation.
