### ISSUE TITLE
Guide/Error-Handling issue

### ISSUE THREAD

**Issue by eyalcohen4** [expressjs/expressjs.com#876]
Hey, 
While making sample app, I tried to use the error middleware described [here](http://expressjs.com/en/guide/error-handling.html).
The first section featured a response using 

    app.use(function (err, req, res, next) {
          console.error(err.stack)
          res.status(500).send('Something broke!')
    })

When I tried to use this middleware in **4.16.2** version, I got `Unexpected 'S'` as a result.
After changing the send method to use an object, everything works well.

    app.use(function (err, req, res, next) {
          console.error(err.stack)
          res.status(500).send({ message: 'Something broke!' })
    })

Maybe this is already a known migration or something, Just reporting anyway

Thanks!

**Comment by crandmck** [comment]
I didn't test this myself (yet), but if this is indeed correct, then we also need to change http://expressjs.com/en/4x/api.html#res.status, which says that `res.status(<number>).send()` takes a string arg.

It also says it is "...a chainable alias of Node’s [ response.statusCode.](http://nodejs.org/api/http.html#http_response_statuscode)" but that doesn't seem right since that's a property not a method.  

Should this instead link to https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers ?

**Comment by ryhinchey** [comment]
I'm testing this in express `4.17.1` and `4.16.2` and cannot replicate.   Closing this issue for now.  If there is really an issue here, it should be raised against  https://github.com/expressjs/express anyways.

**Comment by dougwilson** [comment]
It sounds like the error is in the client side and not the server-side. For example, `res.status(500).send('Something broke!')` would result in the eventual response entity to be `Something broke!` while `res.status(500).send({ message: 'Something broke!' })` would result in `{"message":"Something broke!"}`.

The difference between them is the later is valid JSON while the former is not. Since the client-side error posted is an error from attempting to parse the response entity as JSON, that is just a configuration outside of Express itself, and you just need to be sure that the server sends what the client expects.
