### ISSUE TITLE
NSP is going to shut down, should that section be updated in the docs then?

### ISSUE THREAD

**Issue by noobling** [expressjs/expressjs.com#946]

**Comment by crandmck** [comment]
Thanks for the heads up @noobling ...

However, the tool still works and the site says 
> The service remains operational for current accountholders.

So I would assume the instructions we have in http://expressjs.com/en/advanced/best-practice-security.html#ensure-your-dependencies-are-secure are still valid.  Since it was acquired by npm, Inc., I would assume that it's functionality will be integrated into the `npm` command at some point.  When that happens we can update our doc accordingly.

I'm going to close this, but if my assumptions above are incorrect, please explain and I will re-open.
