### ISSUE TITLE
Add list of template engines to docs

### ISSUE THREAD

**Issue by bgub** [expressjs/expressjs.com#983]
There's a list of template engines in the Express Wiki, but it looks like it hasn't been recently updated.

Can we put a list of compatible (and maintained) template engines for Express on the website, maybe under Resources or Guides?

I would love to help with this issue.

**Comment by dougwilson** [comment]
Yes, that would be great. Ideally everything in the Express wiki is moved to the website. I wouldn't do this all at once, but each at a time would be great, and template engines are a great start!

Since there is a `Middleware` page under Resources I think it makes sense for this to be like a new page under Resources as well.

@LinusU @wesleytodd @crandmck do you have any thoughts?

**Comment by LinusU** [comment]
Sounds very good 👍

**Comment by wesleytodd** [comment]
Agreed!  I think we should also avoid having much info there other than links out.  Just so that we don't have too much work maintaining it so it does not get out of date.

Can you link to this list?  I cant seem to find it just browsing the wiki.

PS. On a side note, alot of that content in the wiki can probably go away.  For example, I doubt we should be pointing people to [books written in 2013](https://github.com/expressjs/expressjs.com/wiki/Books-on-Express) :)

**Comment by bgub** [comment]
@wesleytodd you can just scroll down on the main page of the wiki.

**Comment by wesleytodd** [comment]
Oh sorry, I was looking at this repo's wiki (the website).  I knew I was looking in the wrong place, just forgot about the main express repo's wiki.  Thanks.

**Comment by bgub** [comment]
@wesleytodd no problem.

**Comment by bgub** [comment]
@dougwilson, @LinusU, and @wesleytodd should I fork the repository and start working?

**Comment by wesleytodd** [comment]
Go for it!

**Comment by crandmck** [comment]
Good suggestion!

> Since there is a Middleware page under Resources I think it makes sense for this to be like a new page under Resources as well.

Agree.

When this new page is created, please replace the link to https://github.com/strongloop/express/wiki#template-engines on
http://expressjs.com/en/guide/using-template-engines.html with a link to the new page.

@nebrelbug Note that the [wiki page](https://github.com/strongloop/express/wiki#template-engines) is in markdown format, so you could copy/paste that content _as a starting point_.

**Comment by bgub** [comment]
I've forked the repo and made a page, now I just need to edit the Markdown. Hopefully I'll have it done by tommorow :)

**Comment by bgub** [comment]
@dougwilson @wesleytodd @crandmck So sorry I took so long! Just made pull request #991. It runs on my computer, so I don't think there are any bugs. Thanks!

**Comment by dougwilson** [comment]
This was resolved by PR #991
